# Generated by Django 3.1 on 2024-04-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20240421_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='detalle',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
