# Generated by Django 3.1 on 2024-04-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_producto_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='detalle',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
